### ISSUE TITLE
NPE in France North East Provider

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#107]
```
09-02 12:24:07.911 W/System.err: java.lang.NullPointerException
09-02 12:24:07.911 W/System.err:     at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.dto.Style.parseColor(Style.java:116)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.FranceNorthEastProvider.getLineStyle(FranceNorthEastProvider.java:66)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseLineFromSection(AbstractNavitiaProvider.java:494)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseLeg(AbstractNavitiaProvider.java:565)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.parseQueryTripsResult(AbstractNavitiaProvider.java:658)
09-02 12:24:07.911 W/System.err:     at de.schildbach.pte.AbstractNavitiaProvider.queryTrips(AbstractNavitiaProvider.java:1144)
```

**Comment by grote** [comment]
@stragu that's your provider, right? You can reproduce by searching for trips from "Metz, GARE" to "Stasbourg, Kibitzenau".

**Comment by frikilax** [comment]
I also have the issue, again with France north east provider 
I just remembered this is why I don't use Transportr, I just can't...
(I can't give much details right now, but I will later)
