### ISSUE TITLE
RuntimeException 'cannot parse' in AbstractEfaProvider.jsonStopfinderRequest

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#13]
Sometimes, I get this when trying to get auto-complete results in the VRR network for 'Schadow' with latest git master HEAD:
```
Caused by: java.lang.RuntimeException: cannot parse: '{ "parameters": [ { "name":"requestID", "value":"0" }, { "name":"sessionID", "value":"0" } ], "stopFinder": { "message": [ { "name":"code", "value":"-8020" }, { "name":"error", "value":"" } ], "input": { "input":"sch" }, "points": null } }' on http://app.vrr.de/standard/XML_STOPFINDER_REQUEST?outputFormat=JSON&coordOutputFormat=WGS84&locationServerActive=1&type_sf=any&name_sf=sch&SpEncId=0&anyObjFilter_sf=126&reducedAnyPostcodeObjFilter_sf=64&reducedAnyTooManyObjFilter_sf=2&useHouseNumberList=true&anyMaxSizeHitList=500
            at de.schildbach.pte.AbstractEfaProvider.jsonStopfinderRequest(AbstractEfaProvider.java:300)
            at de.schildbach.pte.AbstractEfaProvider.suggestLocations(AbstractEfaProvider.java:705)
Caused by: org.json.JSONException: Value null at points of type org.json.JSONObject$1 cannot be converted to JSONArray
            at org.json.JSON.typeMismatch(JSON.java:100)
            at org.json.JSONObject.getJSONArray(JSONObject.java:588)
            at de.schildbach.pte.AbstractEfaProvider.jsonStopfinderRequest(AbstractEfaProvider.java:284)
            at de.schildbach.pte.AbstractEfaProvider.suggestLocations(AbstractEfaProvider.java:705)
```

**Comment by schildbach** [comment]
I guess this is not an issue any more?

**Comment by grote** [comment]
I tried a few times and can not reproduce this anymore myself.
