### ISSUE TITLE
SFProvider: IllegalStateException: cannot normalize

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#21]
Search trip from "Railey's Market" to "Sausalito" and get this:

```
java.lang.RuntimeException: uncategorized problem while processing http://tripplanner.transit.511.org/mtc/XSLT_TRIP_REQUEST2?outputFormat=XML&coordOutputFormat=WGS84&sessionID=0&requestID=0&language=de&coordListOutputFormat=STRING&type_origin=coord&name_origin=-122.049232:37.550440:WGS84&type_destination=coord&name_destination=-122.480496:37.856952:WGS84&itdDate=20141221&itdTime=0145&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_0=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&inclMOT_11=on&locationServerActive=1&useRealtime=1&useProxFootSearch=1&nextDepsPerLeg=1
 at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2187)
 Caused by: java.lang.IllegalStateException: cannot normalize mot='0' symbol='XAC' name='Fremont / Richmond' long='Train Fremont / Richmond' trainType='null' trainNum='Fremont / Richmond' trainName='null'
 at de.schildbach.pte.AbstractEfaProvider.parseLine(AbstractEfaProvider.java:1389)
 at de.schildbach.pte.SfProvider.parseLine(SfProvider.java:83)
 at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2578)
 at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2179)
```

**Comment by schildbach** [comment]
Fixed a while ago.
