### ISSUE TITLE
Navitia/ParisProvider: Illegal color values

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#234]
In Paris, some color values are invalid. Here is an example of 5-digit values, but I've also seen 1 digit.

stop_point:OIF:SP:41:6360

```
java.lang.IllegalArgumentException: Unknown color: #65284
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at de.schildbach.pte.dto.Style.parseColor(Style.java:109)
	at de.schildbach.pte.AbstractNavitiaProvider.getLineStyle(AbstractNavitiaProvider.java:158)
	at de.schildbach.pte.AbstractNavitiaProvider.parseLine(AbstractNavitiaProvider.java:609)
	at de.schildbach.pte.AbstractNavitiaProvider.queryDepartures(AbstractNavitiaProvider.java:800)
	at de.schildbach.pte.live.AbstractProviderLiveTest.queryDepartures(AbstractProviderLiveTest.java:107)
```

**Comment by schildbach** [comment]
@prhod Do you have an idea about this color value `#65284`? Is it perhaps an error in the source data? Or should it be interpreted as `#065284` or `#652840`? I've also found a case of `#0`.

**Comment by prhod** [comment]
It seems the invalid values comes from the source GTFS. We will try to contact the producer.
As noticed in the issue https://github.com/schildbach/public-transport-enabler/issues/224, we will fix all those irregular values in the new data pipeline.

**Comment by schildbach** [comment]
I assume this issue has since been addressed on the Navitia side (or bejond). Is this correct?

**Comment by prhod** [comment]
We have greatly advanced in our migration. Except in some French region, those kind of errors should not exist anymore. I think this issue can be closed, feel free to poke me if you encounter problems again.

**Comment by schildbach** [comment]
Thanks for the update!
