### ISSUE TITLE
Cannot handle type: TETA

### ISSUE THREAD

**Issue by NTPape** [schildbach/public-transport-enabler#280]
Whenever I try to search for a route in AVV_AACHEN (which currently uses API version `1.18` in their own online route planner) which contains an Anrufsammeltaxi (on-demand transport service) the app crashes. The error logs suggest that its leg type `TETA` is not supported, I would imagine it might stand for teletaxi. Using its own online route planner I was able to extract a simple such connection which you can find below. It does look _very_ similar to the `JNY` type, but I couldn't find any documentation. Maybe someone can find out more about it.

```
{
  "cid": "C-0",
  "date": "20190916",
  "dur": "000500",
  "chg": 0,
  "sDays": {
    "sDaysR": "Mo - Fr",
    "sDaysI": "nicht 3. Okt, 1. Nov",
    "sDaysB": "7CF9F3E7CF9F3E3CF9F3E7CF9E1E6CF9F3E74F8F3A7CF9F3E7CF9F3E7CF9F3E7CF9D3E7CF9E3E7CF9F3E7C"
  },
  "dep": {
    "locX": 0,
    "idx": 13,
    "dInR": true,
    "dTimeS": "201200",
    "dProgType": "PROGNOSED",
    "type": "N"
  },
  "arr": {
    "locX": 1,
    "aOutR": true,
    "aTimeS": "201700",
    "type": "N"
  },
  "secL": [
    {
      "type": "TETA",
      "icoX": 1,
      "dep": {
        "locX": 0,
        "idx": 13,
        "dInR": true,
        "dTimeS": "201200",
        "dProgType": "PROGNOSED",
        "type": "N"
      },
      "arr": {
        "locX": 1,
        "aOutR": true,
        "aTimeS": "201700",
        "type": "N"
      },
      "jny": {
        "jid": "1|165949|0|80|16092019",
        "prodX": 0,
        "dirTxt": "AST JÜLICH",
        "polyG": {
          "polyXL": [
            0
          ],
          "crdSysX": 1
        },
        "ctxRecon": "T$A=1@O=Aldenhoven, Markt@L=1797@a=128@$A=1@O=Aldenhoven, Engelsdorf AST Ausstieg@L=11794@a=128@$201909162012$201909162016$AST  JÜL$$1$",
        "msgL": [
          {
            "type": "REM",
            "remX": 0,
            "fLocX": 0,
            "tLocX": 2,
            "tagL": [
            "RES_JNY_DTL_H3"
            ]
          },
          {
            "type": "REM",
            "remX": 1,
            "fLocX": 0,
            "tLocX": 2,
            "tagL": [
            "RES_JNY_DTL"
            ]
          }
        ],
        "subscr": "F",
        "prodL": [
          {
            "prodX": 0,
            "fLocX": 0,
            "tLocX": 2,
            "fIdx": 13,
            "tIdx": 16
          }
        ]
      }
    }
  ],
  "ctxRecon": "¶HKI¶T$A=1@O=Aldenhoven, Markt@L=1797@a=128@$A=1@O=Aldenhoven, Engelsdorf AST Ausstieg@L=11794@a=128@$201909162012$201909162016$AST  JÜL$$1$§G@E$A=1@O=Aldenhoven, Engelsdorf AST Ausstieg@L=11794@a=128@$A=1@O=Aldenhoven, Engelsdorf@L=1794@a=128@$201909162016$201909162017$$$1$",
  "conSubscr": "U",
  "recState": "U",
  "cksum": "99be1fb9_3",
  "cksumDti": "0fc3e8c8_3"
}
```

For completeness sake, here the error:
```
java.lang.RuntimeException: uncategorized problem while processing de.schildbach.pte.AbstractHafasClientInterfaceProvider$JsonContext@2e7f3b6 on AVV_AACHEN
	at de.schildbach.oeffi.directions.TripsOverviewActivity$QueryMoreTripsRunnable.doRequest(TripsOverviewActivity.java:351)
	at de.schildbach.oeffi.directions.TripsOverviewActivity$QueryMoreTripsRunnable.run(TripsOverviewActivity.java:269)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.IllegalStateException: cannot handle type: TETA
	at de.schildbach.pte.AbstractHafasClientInterfaceProvider.jsonTripSearch(AbstractHafasClientInterfaceProvider.java:736)
	at de.schildbach.pte.AbstractHafasClientInterfaceProvider.queryMoreTrips(AbstractHafasClientInterfaceProvider.java:216)
	at de.schildbach.oeffi.directions.TripsOverviewActivity$QueryMoreTripsRunnable.doRequest(TripsOverviewActivity.java:289)
	... 5 common frames omitted
```

**Comment by schildbach** [comment]
Fixed via b1fc17c518b8980de23d5b50dee48cb419b95655.
