### ISSUE TITLE
VRS: SignatureException on Android 2.3.3

### ISSUE THREAD

**Issue by schildbach** [schildbach/public-transport-enabler#37]
java.lang.RuntimeException: IO problem while processing de.schildbach.oeffi.directions.DirectionsActivity$23[f:Location{STATION, 18, place=Köln-Innenstadt, name=Chlodwigplatz}|v:null|t:Location{STATION, 35, place=Köln-Innenstadt, name=Ebertplatz}|depart in 0 min|[ON_DEMAND, CABLECAR, BUS, SUBURBAN_TRAIN, SUBWAY, FERRY, REGIONAL_TRAIN, TRAM]|NORMAL|NEUTRAL] on de.schildbach.pte.VrsProvider@40637650 (try 4)
at de.schildbach.oeffi.directions.QueryTripsRunnable.run(QueryTripsRunnable.java:140)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by: javax.net.ssl.SSLHandshakeException: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:477)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
at org.apache.harmony.luni.internal.net.www.protocol.http.HttpConnection.setupSecureSocket(HttpConnection.java:185)
at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:433)
at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl$HttpsEngine.makeConnection(HttpsURLConnectionImpl.java:378)
at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1018)
at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:726)
at org.apache.harmony.luni.internal.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:121)
at de.schildbach.pte.util.ParserUtils.scrapeInputStream(ParserUtils.java:182)
at de.schildbach.pte.util.ParserUtils.scrape(ParserUtils.java:98)
at de.schildbach.pte.util.ParserUtils.scrape(ParserUtils.java:88)
at de.schildbach.pte.util.ParserUtils.scrape(ParserUtils.java:82)
at de.schildbach.pte.VrsProvider.queryTrips(VrsProvider.java:746)
at de.schildbach.oeffi.directions.QueryTripsRunnable.run(QueryTripsRunnable.java:93)
... 4 more
Caused by: java.security.cert.CertificateException: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:161)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:664)
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:474)
... 17 more
Caused by: org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate signature.
at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1504)
at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:399)
at java.security.cert.CertPathValidator.validate(CertPathValidator.java:197)
at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:156)
... 20 more
Caused by: java.security.SignatureException: Signature was not verified
at org.apache.harmony.security.provider.cert.X509CertImpl.fastVerify(X509CertImpl.java:562)
at org.apache.harmony.security.provider.cert.X509CertImpl.verify(X509CertImpl.java:487)
at org.bouncycastle.jce.provider.CertPathValidatorUtilities.verifyX509Certificate(CertPathValidatorUtilities.java:1551)
at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1496)
... 23 more

**Comment by schildbach** [comment]
The issue is reproducable on my Nexus One.

@mdyrna

**Comment by mdyrna** [comment]
You mean it reproducible every time even with a stable Internet connection?

**Comment by schildbach** [comment]
I tried only once but it crashed immediately.

I'm thinking of disabling certificate validation for Android 2.3.

**Comment by mdyrna** [comment]
What happens if you open https://www.vrsinfo.de in your browser on Android 2.3?

**Comment by mdyrna** [comment]
The certificate chain is the following:

(root)
CN = GeoTrust Primary Certification Authority
O = GeoTrust Inc.
C = US
-
CN = GeoTrust EV SSL CA - G4
O = GeoTrust Inc.
C = US
-
CN = www.vrsinfo.de
OU = Informationstechnologie
O = Verkehrsverbund Rhein-Sieg GmbH
L = Koeln
ST = Nordrhein-Westfalen
C = DE
Object Identifier (2 5 4 5) = HRB 16883
Object Identifier (2 5 4 15) = Private Organization
Object Identifier (1 3 6 1 4 1 311 60 2 1 1) = Koeln
Object Identifier (1 3 6 1 4 1 311 60 2 1 3) = DE

GeoTrust claims that Android >= 2.3 should include their root certificate:
https://www.geocerts.com/ssl/browsers

I can't test it myself since my last Android 2.3 device is long gone. :-)

**Comment by schildbach** [comment]
It redirects to https://m.vrsinfo.de/ and that page shows a broken lock. However, Options > Page info > View certificate claims the cert is valid. I'm not sure but I guess the browser is separate to the Java HTTP client.

**Comment by mdyrna** [comment]
So the conclusion is you will disable certificate validation in de.schildbach.pte.util.ParserUtils for Android < 3?

**Comment by schildbach** [comment]
That's my suggestion, yes. Sadly Android 2.3 is still at 10% of the installed user base. But at least they'd get opportunistic encryption.

**Comment by schildbach** [comment]
I was able to work around this issue in Öffi.
