### ISSUE TITLE
GvhProvider: MalformedURLException

### ISSUE THREAD

**Issue by grote** [schildbach/public-transport-enabler#53]
The GVH Provider seems to be broken at the moment. It does not do location auto-completion anymore:

```
java.net.MalformedURLException: Protocol not found: C2C_User=ASBXML_STOPFINDER_REQUEST?outputFormat=JSON&language=de&stateless=1&coordOutputFormat=WGS84&locationServerActive=1&regionID_sf=1&type_sf=any&name_sf=test&anyObjFilter_sf=126&reducedAnyPostcodeObjFilter_sf=64&reducedAnyTooManyObjFilter_sf=2&useHouseNumberList=true&anyMaxSizeHitList=500
     at java.net.URL.<init>(URL.java:176)
     at java.net.URL.<init>(URL.java:125)
     at de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:134)
     at de.schildbach.pte.util.HttpClient.get(HttpClient.java:105)
     at de.schildbach.pte.util.HttpClient.get(HttpClient.java:95)
     at de.schildbach.pte.AbstractEfaProvider.jsonStopfinderRequest(AbstractEfaProvider.java:272)
     at de.schildbach.pte.AbstractEfaProvider.suggestLocations(AbstractEfaProvider.java:708)
```

And with ambiguous locations, it does not find trips:

```
java.net.MalformedURLException: Protocol not found: C2C_User=ASBXSLT_TRIP_REQUEST2?outputFormat=XML&language=de&stateless=1&coordOutputFormat=WGS84&sessionID=0&requestID=0&coordListOutputFormat=STRING&type_origin=any&name_origin=tesz&type_destination=any&name_destination=test&itdDate=20151206&itdTime=1659&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&routeType=LEASTTIME&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_0=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&useProxFootSearch=1&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1
     at java.net.URL.<init>(URL.java:176)
     at java.net.URL.<init>(URL.java:125)
     at de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:134)
     at de.schildbach.pte.util.HttpClient.getInputStream(HttpClient.java:119)
     at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2166)
```

**Comment by schildbach** [comment]
Hmm, the suggestLocation unit tests run fine?

**Comment by grote** [comment]
Sorry for the noise. Your comment made me to investigate this deeper and it was actually me not adapting properly to 2be92e3. I should review your commits more carefully.
