### ISSUE TITLE
INSA (MDV, Saxony/Saxony-Anhalt etc.) search cannot search for adresses anymore

### ISSUE THREAD

**Issue by rugk** [schildbach/public-transport-enabler#593]
## STR

1. In Transportr or Öffi select INSA as the transport network.
2. Try to enter an address (note the autocomplete even shows it)
3. Try to calculate the route.

What happens: Cannot find the start and/or end destination depending on what you've entered.
What should happen: Calculate from any address too, this has AFAIK/IIRC worked in the past (several months or so ago, sorry for late reporting).

### Screenshots 
![Screenshot_20240831-123507](https://github.com/user-attachments/assets/7284f46b-eed5-41ab-aa98-df675b5aa86c)
![Screenshot_20240831-123551](https://github.com/user-attachments/assets/ce4cff2b-4d38-455b-bc7e-ced8543e15fd)

**Comment by leo-liar** [comment]
Is there anyway to troubleshoot this issue or to provide further information for fixing this as a common user?

**Comment by derhuerst** [comment]
FWIW, doing this in [`hafas-client`](https://github.com/public-transport/hafas-client) doesn't work either: I can query locations but fetching connections to/from them doesn't work.

<details>
<summary>log</summary>

```
~/web/hafas-client $ ./tools/debug-cli/cli.js insa locations 'hbf' '{results: 1}' | jq
{"lang":"de","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"LocMatch","req":{"input":{"loc":{"type":"ALL","name":"hbf?"},"maxLoc":1,"field":"S"}}}],"client":{"type":"IPH","id":"NASA","v":"4000200","name":"nasaPROD"},"ver":"1.44","auth":{"type":"AID","aid":"nasa-apps"}}
{"ver":"1.44","lang":"deu","id":"i5ggzhu2miufy6cs","err":"OK","cInfo":{"code":"VH","msg":"Momentan werden die Ticketingfunktionen überarbeitet. Mit dem nächsten Update stehen Ihnen die Funktionen wieder zur Verfügung."},"graph":{"id":"standard","index":0},"subGraph":{"id":"global","index":0},"view":{"id":"standard","index":0,"type":"WGS84"},"svcResL":[{"meth":"LocMatch","err":"OK","res":{"common":{"icoL":[{"res":"prod_ice","fg":{"r":255,"g":255,"b":255},"bg":{"r":0,"g":94,"b":168}}]},"match":{"field":"S","state":"F","locL":[{"lid":"A=1@O=Halle (Saale), Hbf@X=11987080@Y=51477501@U=80@L=90053@B=1@p=1743521097@","type":"S","name":"Halle (Saale), Hbf","icoX":0,"extId":"90053","state":"F","crd":{"x":11987080,"y":51477501,"floor":0},"meta":true,"pCls":255,"wt":32265,"TZOffset":120,"chgTime":"000300"}]}}}]}
[
  {
    "type": "stop",
    "id": "90053",
    "name": "Halle (Saale), Hbf",
    "location": {
      "type": "location",
      "id": "90053",
      "latitude": 51.477501,
      "longitude": 11.98708
    },
    "products": {
      "nationalExpress": true,
      "national": true,
      "regional": true,
      "suburban": true,
      "tram": true,
      "bus": true,
      "tourismTrain": false
    },
    "isMeta": true
  }
]
~/web/hafas-client $ ./tools/debug-cli/cli.js insa locations 'gutenbergplatz 2' '{results: 1}' | jq
{"lang":"de","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"LocMatch","req":{"input":{"loc":{"type":"ALL","name":"gutenbergplatz 2?"},"maxLoc":1,"field":"S"}}}],"client":{"type":"IPH","id":"NASA","v":"4000200","name":"nasaPROD"},"ver":"1.44","auth":{"type":"AID","aid":"nasa-apps"}}
{"ver":"1.44","lang":"deu","id":"88kknha2miufwmcs","err":"OK","cInfo":{"code":"VH","msg":"Momentan werden die Ticketingfunktionen überarbeitet. Mit dem nächsten Update stehen Ihnen die Funktionen wieder zur Verfügung."},"graph":{"id":"standard","index":0},"subGraph":{"id":"global","index":0},"view":{"id":"standard","index":0,"type":"WGS84"},"svcResL":[{"meth":"LocMatch","err":"OK","res":{"common":{"icoL":[{"res":"loc_addr"}]},"match":{"field":"S","state":"F","locL":[{"lid":"A=2@O=Leipzig - Zentrum, Gutenbergplatz 2@H=2@X=12393023@Y=51336613@U=103@L=980753591@B=1@p=1520432662@","type":"A","name":"Leipzig - Zentrum, Gutenbergplatz 2","icoX":0,"extId":"980753591","state":"F","crd":{"x":12393023,"y":51336613}}]}}}]}
[
  {
    "type": "location",
    "id": "980753591",
    "latitude": 51.336613,
    "longitude": 12.393023,
    "address": "Leipzig - Zentrum, Gutenbergplatz 2"
  }
]
~/web/hafas-client $ ./tools/debug-cli/cli.js insa journeys 90053 980753591 '{results: 1}' | jq
{"lang":"de","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"TripSearch","req":{"getPasslist":false,"maxChg":-1,"minChgTime":0,"depLocL":[{"type":"S","lid":"A=1@L=90053@"}],"viaLocL":[],"arrLocL":[{"type":"S","lid":"A=1@L=980753591@"}],"jnyFltrL":[{"type":"PROD","mode":"INC","value":"507"},{"type":"META","mode":"INC","meta":"notBarrierfree"}],"gisFltrL":[],"getTariff":false,"ushrp":true,"getPT":true,"getIV":false,"getPolyline":false,"outDate":"20250403","outTime":"130421","numF":1,"outFrwd":true}}],"client":{"type":"IPH","id":"NASA","v":"4000200","name":"nasaPROD"},"ver":"1.44","auth":{"type":"AID","aid":"nasa-apps"}}
{"ver":"1.44","lang":"deu","id":"382wdhuimiu6864s","err":"OK","cInfo":{"code":"VH","msg":"Momentan werden die Ticketingfunktionen überarbeitet. Mit dem nächsten Update stehen Ihnen die Funktionen wieder zur Verfügung."},"graph":{"id":"standard","index":0},"subGraph":{"id":"global","index":0},"view":{"id":"standard","index":0,"type":"WGS84"},"svcResL":[{"meth":"TripSearch","err":"LOCATION","errTxt":"HCI Service: location missing or invalid","errTxtOut":"Während der Suche ist ein interner Fehler aufgetreten"}]}
file:///Users/j/web/hafas-client/lib/request.js:110
		throw new HafasError(message, body.svcResL[0].err, {...errProps, ...props});
		      ^

HafasNotFoundError: LOCATION: location/stop not found
    at checkIfResponseIsOk (file:///Users/j/web/hafas-client/lib/request.js:110:9)
    at Object.request (file:///Users/j/web/hafas-client/lib/request.js:206:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async journeys (file:///Users/j/web/hafas-client/index.js:247:25)
    at async file:///Users/j/web/hafas-client/tools/debug-cli/cli.js:75:14 {
  isHafasError: true,
  code: 'NOT_FOUND',
  isCausedByServer: false,
  hafasCode: 'LOCATION',
  request: Request {
    size: 0,
    timeout: 0,
    follow: 20,
    compress: true,
    counter: 0,
    agent: Agent {
      _events: [Object: null prototype] {
        free: [Function (anonymous)],
        newListener: [Function: maybeEnableKeylog]
      },
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype] {
        keepAlive: true,
        noDelay: true,
        path: null
      },
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {
        'reiseauskunft.insa.de:443:::::::::::::::::::::': [
          TLSSocket {
            _tlsOptions: [Object],
            _secureEstablished: true,
            _securePending: false,
            _newSessionPending: false,
            _controlReleased: true,
            secureConnecting: false,
            _SNICallback: null,
            servername: 'reiseauskunft.insa.de',
            alpnProtocol: false,
            authorized: true,
            authorizationError: null,
            encrypted: true,
            _events: [Object: null prototype],
            _eventsCount: 9,
            connecting: false,
            _hadError: false,
            _parent: null,
            _host: 'reiseauskunft.insa.de',
            _closeAfterHandlingError: false,
            _readableState: [ReadableState],
            _writableState: [WritableState],
            allowHalfOpen: false,
            _maxListeners: undefined,
            _sockname: null,
            _pendingData: null,
            _pendingEncoding: '',
            server: undefined,
            _server: null,
            ssl: [TLSWrap],
            _requestCert: true,
            _rejectUnauthorized: true,
            parser: null,
            _httpMessage: null,
            timeout: 0,
            [Symbol(alpncallback)]: null,
            [Symbol(res)]: [TLSWrap],
            [Symbol(verified)]: true,
            [Symbol(pendingSession)]: null,
            [Symbol(async_id_symbol)]: -1,
            [Symbol(kHandle)]: [TLSWrap],
            [Symbol(lastWriteQueueSize)]: 0,
            [Symbol(timeout)]: null,
            [Symbol(kBuffer)]: null,
            [Symbol(kBufferCb)]: null,
            [Symbol(kBufferGen)]: null,
            [Symbol(shapeMode)]: true,
            [Symbol(kCapture)]: false,
            [Symbol(kSetNoDelay)]: false,
            [Symbol(kSetKeepAlive)]: true,
            [Symbol(kSetKeepAliveInitialDelay)]: 1,
            [Symbol(kBytesRead)]: 0,
            [Symbol(kBytesWritten)]: 0,
            [Symbol(connect-options)]: [Object]
          }
        ]
      },
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: {
        map: {
          'reiseauskunft.insa.de:443:::::::::::::::::::::': Buffer(1837) [Uint8Array] [
             48, 130,   7,  41,   2,   1,   1,   2,   2,   3,   4,   4,
              2,  19,   2,   4,  32, 225,  75, 228,   5, 209, 132, 254,
            240,  48, 237, 251, 230, 161, 228, 194, 148,  67,  73,  37,
             21, 225, 114, 193,  66,  10,  42,   4,  70,  20, 208,  21,
             37,   4,  48, 250,  64,  75,  38,   7, 251, 129, 244, 143,
            124, 164, 235, 215,  94, 148, 127, 176,  46, 153, 185, 123,
            227,   5, 249, 213,  59, 112,  79, 251,  40, 192, 153,  88,
            130, 114,  78, 246, 160, 116, 214, 146, 104, 158, 131, 188,
             52, 140,  47, 161,
            ... 1737 more items
          ]
        },
        list: [ 'reiseauskunft.insa.de:443:::::::::::::::::::::' ]
      },
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    [Symbol(Body internals)]: {
      body: Buffer(621) [Uint8Array] [
        123,  34, 108,  97, 110, 103,  34,  58,  34, 100, 101,  34,
         44,  34, 115, 118,  99,  82, 101, 113,  76,  34,  58,  91,
        123,  34,  99, 102, 103,  34,  58, 123,  34, 112, 111, 108,
        121,  69, 110,  99,  34,  58,  34,  71,  80,  65,  34, 125,
         44,  34, 109, 101, 116, 104,  34,  58,  34,  84, 114, 105,
        112,  83, 101,  97, 114,  99, 104,  34,  44,  34, 114, 101,
        113,  34,  58, 123,  34, 103, 101, 116,  80,  97, 115, 115,
        108, 105, 115, 116,  34,  58, 102,  97, 108, 115, 101,  44,
         34, 109,  97, 120,
        ... 521 more items
      ],
      disturbed: false,
      error: null
    },
    [Symbol(Request internals)]: {
      method: 'POST',
      redirect: 'follow',
      headers: Headers {
        [Symbol(map)]: [Object: null prototype] {
          'Content-Type': [ 'application/json' ],
          'Accept-Encoding': [ 'gzip, br, deflate' ],
          Accept: [ 'application/json' ],
          'user-agent': [ 'hafas-b9435fclientb9435f debug CLb9435fI' ],
          connection: [ 'keep-alive' ]
        }
      },
      parsedURL: Url {
        protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'reiseauskunft.insa.de',
        port: null,
        hostname: 'reiseauskunft.insa.de',
        hash: null,
        search: '?',
        query: '',
        pathname: '/bin/mgate.exe',
        path: '/bin/mgate.exe?',
        href: 'https://reiseauskunft.insa.de/bin/mgate.exe?'
      },
      signal: null
    }
  },
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: {
      body: Gunzip {
        _writeState: Uint32Array(2) [ 15866, 0 ],
        _events: {
          close: undefined,
          error: [ [Function (anonymous)], [Function (anonymous)] ],
          prefinish: [Function: prefinish],
          finish: undefined,
          drain: undefined,
          data: [Function (anonymous)],
          end: [Function (anonymous)],
          readable: undefined,
          unpipe: undefined
        },
        _readableState: ReadableState {
          highWaterMark: 65536,
          buffer: [],
          bufferIndex: 0,
          length: 0,
          pipes: [],
          awaitDrainWriters: null,
          [Symbol(kState)]: 194512764
        },
        _writableState: WritableState {
          highWaterMark: 65536,
          length: 0,
          corked: 0,
          onwrite: [Function: bound onwrite],
          writelen: 0,
          bufferedIndex: 0,
          pendingcb: 0,
          [Symbol(kState)]: 1091466620,
          [Symbol(kBufferedValue)]: null,
          [Symbol(kWriteCbValue)]: null
        },
        allowHalfOpen: true,
        _maxListeners: undefined,
        _eventsCount: 4,
        bytesWritten: 357,
        _handle: null,
        _outBuffer: Buffer(16384) [Uint8Array] [
          123,  34, 118, 101, 114,  34,  58,  34,  49,  46,  52,  52,
           34,  44,  34, 108,  97, 110, 103,  34,  58,  34, 100, 101,
          117,  34,  44,  34, 105, 100,  34,  58,  34,  51,  56,  50,
          119, 100, 104, 117, 105, 109, 105, 117,  54,  56,  54,  52,
          115,  34,  44,  34, 101, 114, 114,  34,  58,  34,  79,  75,
           34,  44,  34,  99,  73, 110, 102, 111,  34,  58, 123,  34,
           99, 111, 100, 101,  34,  58,  34,  86,  72,  34,  44,  34,
          109, 115, 103,  34,  58,  34,  77, 111, 109, 101, 110, 116,
           97, 110,  32, 119,
          ... 16284 more items
        ],
        _outOffset: 518,
        _chunkSize: 16384,
        _defaultFlushFlag: 2,
        _finishFlushFlag: 2,
        _defaultFullFlushFlag: 3,
        _info: undefined,
        _maxOutputLength: 9007199254740991,
        _level: -1,
        _strategy: 0,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null,
        [Symbol(kError)]: null
      },
      disturbed: true,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://reiseauskunft.insa.de/bin/mgate.exe?',
      status: 200,
      statusText: 'OK',
      headers: Headers {
        [Symbol(map)]: [Object: null prototype] {
          date: [ 'Thu, 03 Apr 2025 11:04:21 GMT' ],
          server: [ 'Apache/2.4.62 (Debian)' ],
          'content-encoding': [ 'gzip' ],
          generator: [ 'mgate/engine' ],
          'access-control-allow-origin': [ '*' ],
          'keep-alive': [ 'timeout=5, max=100' ],
          connection: [ 'Keep-Alive' ],
          'transfer-encoding': [ 'chunked' ],
          'content-type': [ 'application/json; charset=utf-8' ]
        }
      },
      counter: 0
    }
  },
  url: 'https://reiseauskunft.insa.de/bin/mgate.exe?',
  hafasResponseId: '382wdhuimiu6864s',
  hafasMessage: 'HCI Service: location missing or invalid',
  hafasDescription: 'Während der Suche ist ein interner Fehler aufgetreten'
}

Node.js v23.7.0
```

</details>

**Comment by rugk** [comment]
I can confirm this is unrelated to the linked issue. The error still happens and the exception/error is still a different one. (it is still "Unknown start or end endpoint.")

**Comment by leo-liar** [comment]
Thanks for reopening and yes, I've installed right now Öffi in version 13.0.17130017 from 19.11.2025.
_(According to Obtainium this is the most recent version available on [https://oeffi.schildbach.de/download_de.html](https://oeffi.schildbach.de/downloads/oeffi-13.0.17.apk).)_

I just tried the route to and from the locations in the first post with the following result:
<details>
<summary>Screenshot</summary>
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/db0a3890-d085-49f3-bf66-0281f2d70628" />
</details>
