### ISSUE TITLE
KVV: expecting attribute: project

### ISSUE THREAD

**Issue by ByteHamster** [schildbach/public-transport-enabler#63]
The KVV provider stopped working some days ago. Unfortunately, I don't know enough about pte to fix it on my own. Would be great if someone could have a look at it :) 

```
W/System.err(32605): java.lang.RuntimeException: uncategorized problem while processing http://213.144.24.66/oeffi/XSLT_TRIP_REQUEST2?outputFormat=XML&language=de&stateless=1&coordOutputFormat=WGS84&sessionID=0&requestID=0&coordListOutputFormat=STRING&type_origin=stop&name_origin=7000089&type_destination=stop&name_destination=7000073&itdDate=20160109&itdTime=2313&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&routeType=LEASTTIME&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_0=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&useProxFootSearch=1&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1
W/System.err(32605): 	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2166)
W/System.err(32605): 	at de.grobox.liberario.tasks.AsyncQueryTripsTask.doInBackground(AsyncQueryTripsTask.java:99)
W/System.err(32605): 	at de.grobox.liberario.tasks.AsyncQueryTripsTask.doInBackground(AsyncQueryTripsTask.java:41)
W/System.err(32605): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err(32605): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(32605): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(32605): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(32605): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(32605): 	at java.lang.Thread.run(Thread.java:818)
W/System.err(32605): Caused by: java.lang.IllegalStateException: expecting attribute: project
W/System.err(32605): 	at de.schildbach.pte.util.XmlPullUtil.attr(XmlPullUtil.java:133)
W/System.err(32605): 	at de.schildbach.pte.AbstractEfaProvider.processPublicLeg(AbstractEfaProvider.java:2662)
W/System.err(32605): 	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2486)
W/System.err(32605): 	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2158)
W/System.err(32605): 	... 8 more
```

**Comment by schildbach** [comment]
Fixed via f4a360615f56113b1973743b74ebe0af3afc970b.
