### ISSUE TITLE
Provider VRR issue

### ISSUE THREAD

**Issue by pkalbrun-goeuro** [schildbach/public-transport-enabler#92]
Hi,
Found problem with VRR provider:

```
java.lang.RuntimeException: uncategorized problem while processing http://efa.vrr.de/standard/XSLT_TRIP_REQUEST2?outputFormat=XML&language=de&stateless=1&coordOutputFormat=WGS84&sessionID=0&requestID=0&coordListOutputFormat=STRING&type_origin=stop&name_origin=20018235&type_destination=stop&name_destination=22000892&itdDate=20160714&itdTime=0800&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_0=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1&inclMOT_11=on 
at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2187) 
...
Caused by: java.lang.IllegalStateException: cannot normalize mot='0' symbol='RE6a' name='RE6a' long='R-Bahn RE6a' trainType='null' trainNum='RE6a' trainName='null' 
at de.schildbach.pte.AbstractEfaProvider.parseLine(AbstractEfaProvider.java:1487) 
at de.schildbach.pte.VrrProvider.parseLine(VrrProvider.java:111)
 at de.schildbach.pte.AbstractEfaProvider.processPublicLeg(AbstractEfaProvider.java:2693) 
at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2509) 
at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2179) ... 15 more
```

**Comment by schildbach** [comment]
What commit are you on? This should be fixed since quite some time already…

**Comment by pkalbrun-goeuro** [comment]
Hi, it was happening on d245c29.

**Comment by schildbach** [comment]
Ok thanks. I believe it's fixed on master.
