### ISSUE TITLE
EFA provider issue

### ISSUE THREAD

**Issue by pkalbrun-goeuro** [schildbach/public-transport-enabler#93]
Hi, 
found an issue with EFA provider:
```
java.lang.RuntimeException: uncategorized problem while processing http://bhb.efa.de/bhb/XSLT_TRIP_REQUEST2?outputFormat=XML&language=de&stateless=1&coordOutputFormat=WGS84&sessionID=0&requestID=0&coordListOutputFormat=STRING&type_origin=stop&name_origin=90001782&type_destination=stop&name_destination=24035532&itdDate=20160530&itdTime=0800&itdTripDateTimeDepArr=dep&calcNumberOfTrips=6&ptOptionsActive=1&itOptionsActive=1&changeSpeed=normal&includedMeans=checkbox&inclMOT_0=on&inclMOT_0=on&inclMOT_1=on&inclMOT_2=on&inclMOT_3=on&inclMOT_4=on&inclMOT_5=on&inclMOT_6=on&inclMOT_7=on&inclMOT_9=on&inclMOT_8=on&inclMOT_10=on&useProxFootSearch=1&trITMOTvalue100=10&locationServerActive=1&useRealtime=1&nextDepsPerLeg=1
	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2187)
	.....
Caused by: java.lang.IllegalStateException: cannot normalize mot='0' symbol='null' name='74073' long='SE 74073 ABELLIO Rail Mitteldeutschland GmbH' trainType='SE' trainNum='74073' trainName='ABELLIO Rail Mitteldeutschland GmbH'
	at de.schildbach.pte.AbstractEfaProvider.parseLine(AbstractEfaProvider.java:1487)
	at de.schildbach.pte.GvhProvider.parseLine(GvhProvider.java:64)
	at de.schildbach.pte.AbstractEfaProvider.processPublicLeg(AbstractEfaProvider.java:2693)
	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2509)
	at de.schildbach.pte.AbstractEfaProvider.queryTrips(AbstractEfaProvider.java:2179)
	... 21 more
```

**Comment by schildbach** [comment]
What commit are you on? It should be fixed in current master.

**Comment by pkalbrun-goeuro** [comment]
Hi,
it is happening on d245c29.

**Comment by schildbach** [comment]
That's an old commit. I believe it is fixed already. Please retest on master and feel free to comment again if it is still a problem.
